
ALTER TABLE DETAILRENTAL
DROP FOREIGN KEY detailrental_ibfk_1;

ALTER TABLE RENTAL
MODIFY COLUMN RENT_NUM INT AUTO_INCREMENT;

ALTER TABLE DETAILRENTAL
ADD CONSTRAINT detailrental_ibfk_1
FOREIGN KEY (RENT_NUM)
REFERENCES RENTAL(RENT_NUM)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE RENTAL
AUTO_INCREMENT = 1100;





