CREATE TABLE MEMBERSHIP (
    MEM_NUM INT PRIMARY KEY,
    MEM_FNAME VARCHAR(50) ,
    MEM_LNAME VARCHAR(50) ,
    MEM_STREET VARCHAR(100) ,
    MEM_CITY VARCHAR(50) ,
    MEM_STATE CHAR(2) ,
    MEM_ZIP CHAR(5) ,
    MEM_BALANCE DECIMAL(10, 2) 
);


CREATE TABLE RENTAL (
    RENT_NUM INT PRIMARY KEY,
    RENT_DATE DATE ,
    MEM_NUM INT ,
    FOREIGN KEY (MEM_NUM) REFERENCES MEMBERSHIP(MEM_NUM)
);


CREATE TABLE DETAILRENTAL (
    RENT_NUM INT,
    VID_NUM INT ,
    DETAIL_FEE DECIMAL(10, 2) ,
    DETAIL_DUEDATE DATE ,
    DETAIL_RETURNDATE DATE ,
    DETAIL_DAILYLATEFEE INT ,
    PRIMARY KEY (RENT_NUM, VID_NUM),
    FOREIGN KEY (RENT_NUM) REFERENCES RENTAL(RENT_NUM)
);


CREATE TABLE MOVIE (
    MOVIE_NUM INT PRIMARY KEY,
    MOVIE_TITLE VARCHAR(100) ,
    MOVIE_YEAR INT ,
    MOVIE_COST DECIMAL(10, 2) ,
    MOVIE_GENRE VARCHAR(50) ,
    PRICE_CODE INT 
);


CREATE TABLE VIDEO (
    VID_NUM INT PRIMARY KEY,
    VID_INDATE DATE NOT NULL,
    MOVIE_NUM INT NOT NULL,
    FOREIGN KEY (MOVIE_NUM) REFERENCES MOVIE(MOVIE_NUM)
);

CREATE TABLE PRICE (
    PRICE_CODE INT PRIMARY KEY,
    PRICE_DESCRIPT varchar(100),
    PRICE_RENTFEE decimal(10,2) NOT NULL,
    PRICE_DAILYLATEFEE decimal(10,2)
);


